coverage:
  precision: 3
  round: down
  range: "80...100"

  notify:
    gitter:
      default:
        url: https://webhooks.gitter.im/e/b688071667f9bb1d01e2

  status:
    project:
      default:
        threshold: 1
